CREATE TABLE MYUSER.DOCUMENT (
    ID VARCHAR2(36) NOT NULL,
    METAS VARCHAR2(512) CONSTRAINT ensure_json CHECK(METAS IS JSON)
);

INSERT INTO MYUSER.DOCUMENT VALUES (SYS_GUID(),'{"nom":"Wilcox","prenom":"Benoit","age":39}');
INSERT INTO MYUSER.DOCUMENT VALUES (SYS_GUID(),'{"nom":"Doe","prenom":"John","age":45}');
